src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompanyRepository::class)]
#[ORM\HasLifecycleCallbacks]

/**
 * Class Company
 * @package App\Entity
 */
class Company
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $registration_code = null;

    #[ORM\Column(length: 50)]
    private ?string $vat = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $mobile_phone = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $created_at;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getRegistrationCode(): ?int
    {
        return $this->registration_code;
    }

    public function setRegistrationCode(int $registration_code): static
    {
        $this->registration_code = $registration_code;

        return $this;
    }

    public function getVat(): ?string
    {
        return $this->vat;
    }

    public function setVat(string $vat): static
    {
        $this->vat = $vat;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getMobilePhone(): ?string
    {
        return $this->mobile_phone;
    }

    public function setMobilePhone(?string $mobile_phone): static
    {
        $this->mobile_phone = $mobile_phone;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    #[ORM\PrePersist]
    public function onPrePersist()
    {
        $this->setCreatedAt(new \DateTime("now")) ;
    }

    #[ORM\PreUpdate]
    public function onPreUpdate()
    {
        $this->setUpdatedAt(new \DateTime("now")) ;
    }
}

src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, array(
                    'attr' => array('class' => 'form-control'),
                    'constraints' => [
                        new Assert\NotBlank(),
                        new Assert\Length(['max' => 255]),
                    ],
                )
            )
            ->add('registration_code', IntegerType::class, array(
                    'attr' => array('class' => 'form-control'),
                    'constraints' => [
                        new Assert\NotBlank(),
                        new Assert\Length(['min' => 9]),
                    ],
                )
            )
            ->add('vat', TextType::class, array(
                    'attr' => array('class' => 'form-control'),
                    'constraints' => [
                        new Assert\NotBlank(),
                        new Assert\Length(['max' => 50]),
                    ],
                )
            )
            ->add('address', TextareaType::class, array(
                    'attr' => array('class' => 'form-control'),
                )
            )
            ->add('mobile_phone', TextType::class, array(
                    'attr' => array('class' => 'form-control'),
                    'constraints' => [
                        new Assert\NotBlank(),
                        new Assert\Length(['max' => 30]),
                    ],
                )
            );
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Entity\CompanyTurnover;
use App\Form\CompanyType;
use App\Repository\CompanyRepository;
use App\Repository\CompanyTurnoverRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

#[Route('/company')]
class CompanyController extends AbstractController
{
    protected $entityManager;
    protected $companyTurnoverRepo;

    public function __construct(EntityManagerInterface $entityManager, CompanyTurnoverRepository $companyTurnoverRepo)
    {
        $this->entityManager = $entityManager;
        $this->companyTurnoverRepo = $companyTurnoverRepo;
    }

    #[Route('/', name: 'app_company_index', methods: ['GET'])]
    public function index(Request $request, CompanyRepository $companyRepository, PaginatorInterface $paginator): Response
    {
        $filter = $request->query->get('filter');

        $query = $companyRepository->createQueryBuilder('c');

        if ($filter === 'name_asc') {
            $query = $query->orderBy('c.name', 'ASC');
        } elseif ($filter === 'name_desc') {
            $query = $query->orderBy('c.name', 'DESC');
        } elseif ($filter === 'turnover_asc') {
            $query = $query->orderBy('c.turnover', 'ASC');
        } elseif ($filter === 'turnover_desc') {
            $query = $query->orderBy('c.turnover', 'DESC');
        } else {
            $query = $query->orderBy('c.id', 'DESC');
        }

        $pagination  = $paginator->paginate(
            $query->getQuery(),
            $request->query->getInt('page', 1),
            10 // items per page
        );
        return $this->render('company/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    #[Route('/new', name: 'app_company_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ValidatorInterface $validator): Response
    {
        $company = new Company();
        $form = $this->createForm(CompanyType::class, $company);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($company);
            $this->entityManager->flush();

            return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('company/new.html.twig', [
            'company' => $company,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_company_show', methods: ['GET'])]
    public function show(Company $company): Response
    {
        $companyTurnover = $this->companyTurnoverRepo->findOneBy(['company_id' => $company->getId()]);

        return $this->render('company/show.html.twig', [
            'company' => $company,
            'table'   => $companyTurnover->getData() ?? null
        ]);
    }

    #[Route('/{id}/edit', name: 'app_company_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Company $company): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('company/edit.html.twig', [
            'company' => $company,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_company_delete', methods: ['POST'])]
    public function delete(Request $request, Company $company): Response
    {
        if ($this->isCsrfTokenValid('delete'.$company->getId(), $request->request->get('_token'))) {
            $companyTurnover = $this->companyTurnoverRepo->findOneBy(['company_id' => $company->getId()]);
            $this->entityManager->remove($companyTurnover);
            $this->entityManager->flush();

            $this->entityManager->remove($company);
            $this->entityManager->flush();
        }

        return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/company/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {# Display validation errors #}
        {{ form_errors(form) }}
        <div class="form-group row mt-5">
            <div class="col-sm-10 offset-sm-2" style="text-align: center;">
                <a href="{{ path('app_company_index') }}" type="button" class="btn btn-warning" >Back to List</a>
                <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
            </div>
        </div>
{{ form_end(form) }}

templates/company/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update Company{% endblock %}

{% block body %}
    <div class="container mt-5">
        {{ include('company/_form.html.twig', {'button_label': 'Update'}) }}
    </div>
{% endblock %}

templates/company/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Company index{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="mb-4 d-flex justify-content-between align-items-center">
            <form class="form-inline" method="get">
                <div class="form-group">
                    <div class="form-group mr-2">
                        <label for="filterDropdown" class="mr-2">Sort By:</label>
                        <select id="sort" name="filter" class="form-control">
                            <option value="">Select option</option>
                            <option {% if app.request.query.get('filter') == 'name_asc' %}selected{% endif %} value="name_asc">Name (Ascending)</option>
                            <option {% if app.request.query.get('filter') == 'name_desc' %}selected{% endif %} value="name_desc">Name (Descending)</option>
                        </select>
                    </div>
                </div>
                <button class="btn btn-primary ml-2" type="submit">Apply Filters</button>
            </form>
            <a href="{{ path('app_company_new') }}" class="btn btn-success">Create</a>
        </div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Code</th>
                <th>VAT</th>
                <th>Mobile Phone</th>
                <th>Created</th>
                <th>Updated</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for company in pagination %}
                <tr>
                    <td>{{ company.name }}</td>
                    <td>{{ company.registrationCode }}</td>
                    <td>{{ company.vat }}</td>
                    <td>{{ company.mobilePhone }}</td>
                    <td>{{ company.createdAt ? company.createdAt|date('Y-m-d') : '' }}</td>
                    <td>{{ company.updatedAt ? company.updatedAt|date('Y-m-d') : '' }}</td>
                    <td>
                        <div class="row">
                            <a href="{{ path('app_company_show', {'id': company.id}) }}" class="btn btn-sm btn-info mr-1">Details</a>
                            <a href="{{ path('app_company_edit', {'id': company.id}) }}" class="btn btn-sm btn-warning mr-1">Edit</a>
                            <form method="post" action="{{ path('app_company_delete', {'id': company.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ company.id) }}">
                                <button class="btn btn-sm btn-danger">Delete</button>
                            </form>
                        </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="10">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% if pagination|length %}
        <div class="pagination">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if pagination.currentPageNumber > 1 %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path(pagination.route, pagination.params|merge({'page': pagination.currentPageNumber - 1})) }}">Previous</a>
                        </li>
                    {% endif %}

                    {% for page in range(1, pagination.pageCount) %}
                        <li class="page-item {% if pagination.currentPageNumber == page %}active{% endif %}">
                            <a class="page-link" href="{{ path(pagination.route, pagination.params|merge({'page': page})) }}">{{ page }}</a>
                        </li>
                    {% endfor %}

                    {% if pagination.currentPageNumber < pagination.pageCount %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path(pagination.route, pagination.params|merge({'page': pagination.currentPageNumber + 1})) }}">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        {% endif %}

    </div>
{% endblock %}

templates/company/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Company{% endblock %}

{% block body %}
    <div class="container mt-5">

        {{ include('company/_form.html.twig', {'button_label': 'Create'}) }}
    </div>
{% endblock %}

templates/company/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Company{% endblock %}

{% block body %}
<div class="container mt-3">
    {% if company is defined and company is not null %}
        <fieldset disabled="disabled" class="mb-5">
            <div class="container mt-3">
                <div class="row col-md-12">
                    <div class="col-md-6">
                        <label for="company_name">Name</label><input type="text" id="company_name" class="form-control" value="{{ company.getName() }}" />
                    </div>
                    <div class="col-md-6">
                        <label for="company_registration_code">Registration code</label><input type="number" id="company_registration_code" class="form-control" value="{{ company.getRegistrationCode() }}" />
                    </div>
                </div>
                <div class="row col-md-12">
                    <div class="col-md-6">
                        <label for="company_vat">Vat</label><input type="text" id="company_vat" class="form-control" value="{{ company.getVat() }}" />
                    </div>
                    <div class="col-md-6">
                        <label for="company_mobile_phone">Mobile phone</label><input type="text" id="company_mobile_phone" class="form-control" value="{{ company.getMobilePhone() }}" />
                    </div>

                </div>
                <div class="row col-md-12">
                    <div class="col-md-12">
                        <label for="company_address">Address</label><textarea id="company_address" class="form-control"> {{ company.getAddress() }}</textarea>
                    </div>
                </div>
            </div>
        </fieldset>
    {% endif %}
    {% if table is defined and table is not null %}
        <div>
            <table class="table table-striped">
                <thead>
                <tr>
                    {% for th in table[0] %}
                        <th>{{ th }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for tr in table | slice(1) %}
                    <tr>
                        {% for td in tr %}
                            <td>{{ td }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
    <div class="form-group row mt-5">
        <div class="col-sm-10 offset-sm-2" style="text-align: center;">
            <a href="{{ path('app_company_index') }}" type="button" class="btn btn-warning" >Back to List</a>
        </div>
    </div>
</div>
{% endblock %}